/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const format: typeof import('date-fns')['format']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { SbBlokData } from '@storyblok/nuxt'
  import('@storyblok/nuxt')
  // @ts-ignore
  export type { ISbRichtext } from '@storyblok/vue'
  import('@storyblok/vue')
}
