/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const colors: typeof import('@unocss/preset-mini')['colors']
  const format: typeof import('date-fns')['format']
}
